apiVersion: v1
kind: Service

metadata:
  name: moodle
  labels:
    app: moodle

spec:
  type: ClusterIP
  selector:
    app: moodle
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
