
---
apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  type: ClusterIP
  ports:
  - port: 5000
  
  selector:
    app: moodle

  # nodes IPs - 
  # These IPs are not managed by Kubernetes. 
  # The user is responsible for ensuring that traffic arrives at a node with this IP.
  # -----------------
  externalIPs:
  - "172.20.0.4"
  - "172.20.0.5"